/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atelie.forms;

import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.BorderFactory;
import javax.swing.*;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.NameValuePair;
import org.apache.http.util.EntityUtils;
import java.util.ArrayList;
import java.util.List;
import org.json.JSONObject;

/**
 *
 * @author 8270@stud.pgt.su
 */
public class avtorizacia extends javax.swing.JFrame {

    /**
     * Creates new form avtorizacia
     */
    public avtorizacia() {

        FlatLightLaf.setup();
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/resources/img/icon.png");
        setIconImage(icon.getImage());
        updateEyeIcon(); // Вызываем метод обновления иконки
        this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false); // Если нужно фиксировать размер
    }

    private void initTextFieldStyles() {
        // Стиль для jFormattedTextField1
        jFormattedTextField1.putClientProperty(FlatClientProperties.STYLE,
                "arc: 10;"
                + "background: rgba(255,255,255,0.9);"
                + "borderColor: #cccccc;"
                + "focusWidth: 1;"
                + "showClearButton: true");

        jFormattedTextField1.setBorder(new EmptyBorder(5, 10, 5, 10));
        jFormattedTextField1.setToolTipText("Введите ваш логин");

        // Стиль для jPasswordField1
        jPasswordField1.putClientProperty(FlatClientProperties.STYLE,
                "arc: 10;"
                + "background: rgba(255,255,255,0.9);"
                + "borderColor: #cccccc;"
                + "focusWidth: 1;"
                + "showRevealButton: true");

        jPasswordField1.setBorder(new EmptyBorder(5, 10, 5, 10));
        jPasswordField1.setToolTipText("Введите ваш пароль");
    }

    private void updateEyeIcon() {
        if (jCheckBox1.isSelected()) {
            jCheckBox1.setText("<html>👁</html>");
            jCheckBox1.setToolTipText("Скрыть пароль");
        } else {
            jCheckBox1.setText("<html><strike>👁</strike></html>");
            jCheckBox1.setToolTipText("Показать пароль");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Авторизация");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField1.setForeground(new java.awt.Color(163, 27, 24));
        jFormattedTextField1.setToolTipText("");
        jFormattedTextField1.setName(""); // NOI18N
        jFormattedTextField1.setOpaque(true);
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 200, 40));

        jCheckBox1.setFont(new java.awt.Font("FreeSans", 0, 13)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(163, 27, 24));
        jCheckBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 40, 40));

        jPasswordField1.setForeground(new java.awt.Color(163, 27, 24));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 200, 40));

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(163, 27, 24));
        jButton1.setText("Войти");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 200, 40));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(163, 27, 24));
        jLabel2.setText("Вход");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(163, 27, 24));
        jLabel4.setText("Магазин тканей");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        jPasswordField1.setEchoChar(jCheckBox1.isSelected() ? (char) 0 : '*');
        updateEyeIcon();

        // Устанавливаем темно-зеленый цвет для отмеченного состояния
        jCheckBox1.setForeground(new Color(167, 27, 24)); // Темно-зеленый цвет

        if (jCheckBox1.isSelected()) {
            jCheckBox1.setText("<html>👁</html>"); // Открытый глаз
            jCheckBox1.setToolTipText("Скрыть пароль");
        } else {
            jCheckBox1.setText("<html><strike>👁</strike></html>"); // Зачеркнутый глаз
            jCheckBox1.setToolTipText("Показать пароль");
        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed


    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed

    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String login = jFormattedTextField1.getText();
        String password = new String(jPasswordField1.getPassword());

        // Проверка администратора (если нужно оставить хардкод)
        if (login.equals("admin") && password.equals("admin")) {
            this.dispose();
            new admin1().setVisible(true);
            return;
        }

        try {
            // Создаем HTTP клиент
            CloseableHttpClient httpClient = HttpClients.createDefault();

            // Создаем POST запрос
            HttpPost httpPost = new HttpPost("http://localhost:8080/atelie/getAuthorization");

            // Добавляем параметры
            List<NameValuePair> params = new ArrayList<>();
            params.add(new BasicNameValuePair("Login", login));
            params.add(new BasicNameValuePair("Password", password));
            httpPost.setEntity(new UrlEncodedFormEntity(params, "UTF-8"));

            // Выполняем запрос
            CloseableHttpResponse response = httpClient.execute(httpPost);

            // Обрабатываем ответ
            String responseBody = EntityUtils.toString(response.getEntity());
            int statusCode = response.getStatusLine().getStatusCode();

            // Закрываем соединение
            response.close();
            httpClient.close();

            if (statusCode == 200 && responseBody != null) {
                // Проверяем роль пользователя через дополнительные API запросы
                checkUserRole(login);
            } else {
                JOptionPane.showMessageDialog(this, "Неверный логин/пароль");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ошибка подключения к серверу: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void checkUserRole(String login) {
        try {
            CloseableHttpClient httpClient = HttpClients.createDefault();

            // Сначала получаем ID швеи по логину
            HttpPost getShveyaId = new HttpPost("http://localhost:8080/atelie/getShveyaIdByLogin");
            List<NameValuePair> shveyaIdParams = new ArrayList<>();
            shveyaIdParams.add(new BasicNameValuePair("login", login));
            getShveyaId.setEntity(new UrlEncodedFormEntity(shveyaIdParams, "UTF-8"));

            CloseableHttpResponse shveyaIdResponse = httpClient.execute(getShveyaId);
            String shveyaIdResponseBody = EntityUtils.toString(shveyaIdResponse.getEntity());
            shveyaIdResponse.close();

            // Парсим JSON ответ
            JSONObject shveyaJson = new JSONObject(shveyaIdResponseBody);
            boolean isShveya = shveyaJson.getBoolean("success");

            if (isShveya) {
                int shveyaId = shveyaJson.getInt("shveyaId");
                this.dispose();
                new shveya(shveyaId).setVisible(true); // ПЕРЕДАЕМ ID!
                return;
            }

            // Аналогично для продавца
            HttpPost getProdavecId = new HttpPost("http://localhost:8080/atelie/getProdavecIdByLogin");
            List<NameValuePair> prodavecIdParams = new ArrayList<>();
            prodavecIdParams.add(new BasicNameValuePair("login", login));
            getProdavecId.setEntity(new UrlEncodedFormEntity(prodavecIdParams, "UTF-8"));

            CloseableHttpResponse prodavecIdResponse = httpClient.execute(getProdavecId);
            String prodavecIdResponseBody = EntityUtils.toString(prodavecIdResponse.getEntity());
            prodavecIdResponse.close();

            JSONObject prodavecJson = new JSONObject(prodavecIdResponseBody);
            boolean isProdavec = prodavecJson.getBoolean("success");

            if (isProdavec) {
                int prodavecId = prodavecJson.getInt("prodavecId");
                this.dispose();
                new prodavec(prodavecId).setVisible(true); // ПЕРЕДАЕМ ID!
                return;
            }

            // Аналогично для управляющего
            HttpPost getUpravId = new HttpPost("http://localhost:8080/atelie/getUpravlyayushchiyIdByLogin");
            List<NameValuePair> upravIdParams = new ArrayList<>();
            upravIdParams.add(new BasicNameValuePair("login", login));
            getUpravId.setEntity(new UrlEncodedFormEntity(upravIdParams, "UTF-8"));

            CloseableHttpResponse upravIdResponse = httpClient.execute(getUpravId);
            String upravIdResponseBody = EntityUtils.toString(upravIdResponse.getEntity());
            upravIdResponse.close();

            JSONObject upravJson = new JSONObject(upravIdResponseBody);
            boolean isUpravlyayushchiy = upravJson.getBoolean("success");

            if (isUpravlyayushchiy) {
                int upravId = upravJson.getInt("upravlyayushchiyId");
                this.dispose();
                new upravlyayushchiy(upravId).setVisible(true); // ПЕРЕДАЕМ ID!
                return;
            }

            httpClient.close();

            JOptionPane.showMessageDialog(this, "Пользователь не имеет назначенной роли");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ошибка проверки роли: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(avtorizacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(avtorizacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(avtorizacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(avtorizacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new avtorizacia().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
